.gitignore, Makefile, README.md, apps/api/package.json, apps/api/src/main.ts, apps/web/cypress.json, apps/web/cypress/integration/app.spec.ts, apps/web/package.json, terraform/.gitignore, terraform/main.tf, terraform/s3.tf, terraform/variables.tf, terraform/vpc.tf
#Motivation
https://freshworks.atlassian.net/browse/HAPP-333
https://freshworks.atlassian.net/browse/HAPP-339
=> [HAPP-333] Terraform Setup. 

apps/web/public/locales/en/translation.json, apps/web/public/locales/fr/translation.json, apps/web/public/locales/ko/translation.json, apps/web/public/manifest.json, apps/web/src/components/Footer.tsx, apps/web/src/components/Header.tsx, apps/web/src/components/Home.tsx, apps/web/src/components/Spinner.tsx, apps/web/src/forms/Q3Symptoms.tsx, apps/web/src/i18n.ts, apps/web/src/index.tsx
- preload translations
- remove language selection
- change app name to self-assessment tool
=> Disable language selection

.github/workflows/deploy-dev.yml, .github/workflows/deploy-test.yml
Deployment to AWS as follows: 
tag-dev -> Deploy to dev
tag-test -> Deploy to test
merge to main -> Deploy to test
=> team agreement deploy strategy

apps/web/src/components/HealthLinkBC.tsx, apps/web/src/components/Home.tsx, apps/web/src/components/RadioButtons.tsx, apps/web/src/forms/Q4TestResult.tsx, apps/web/src/forms/SeverityDiarrhea.tsx, apps/web/src/forms/SeverityHeadache.tsx, apps/web/src/forms/SymptomChecker.tsx, apps/web/src/results/ResultAsymptomaticNoTest.tsx, apps/web/src/results/ResultCall811.tsx, apps/web/src/results/ResultPageLayout.tsx, apps/web/src/results/ResultSymptomaticNoTest.tsx, apps/web/src/results/ResultSymptomaticTest.tsx, apps/web/src/types/index.ts
- link 'retake' to the landing page
- make test result question optional
- open links in a new tab
- disable future dates for test date
- scroll to top when changing page
=> Optional question

apps/web/src/components/RadioButtons.tsx, apps/web/src/forms/Q4TestResult.tsx, apps/web/src/images/upend-caret.svg
- fix flickering effect on radio buttons
- make input background for test date and result transparent
- fix inconsistent border for test date and result inputs
=> improve mobile presentations

apps/web/public/locales/en/translation.json, apps/web/src/forms/Q3Symptoms.tsx, apps/web/src/forms/SymptomChecker.tsx, apps/web/src/types/index.ts
- fix error message
- allow going to the previous page by window's back button
=> fix error message of symptom selection page

apps/web/public/locales/en/translation.json
=> SYMP-40 and SYMP-41 | text mismatches

apps/web/public/locales/en/translation.json, apps/web/src/App.tsx, apps/web/src/Layout.tsx, apps/web/src/components/Home.tsx, apps/web/src/forms/SymptomChecker.tsx
Generally removed references to components but did not delete them entirely.
=> SYMP-46-47-48 remove tiles and footer

apps/web/src/utils/anayltics.ts
Updated the values sent to snowplow to be more human readable
=> SYMP-50 Updated copy for snowplow notifications

apps/web/cypress/integration/outcome/outcomes.spec.ts, apps/web/public/locales/en/translation.json, apps/web/src/forms/QuestionSteps.tsx, apps/web/src/forms/SymptomChecker.tsx
Removed the question, updated the tests. Did not scour any trace of it from the codebase.
Just a heads up: SYMP-17 was failing to deploy because of a let that should have been a const, but then the branch was already deleted and the PR is closed... Tacked it on here.
=> SYMP-45 | Remove covid test question

apps/web/public/analytics/snowplow.dev.js, apps/web/src/utils/anayltics.ts, terraform/cloudfront/response.js
Updated Var Collector, but I don't see where we have set casing for selection of "none" on symptoms.
=> SYMP-52-Update Var Collector and Copy for SnowPlow

apps/web/public/locales/en/translation.json, apps/web/src/components/Home.tsx
Added elements back to Home page, put text in translation file
=> SYMP-48 | COVID and children

apps/web/cypress/integration/outcome/outcomes.spec.ts, apps/web/src/forms/SymptomChecker.tsx
Ticket: https://freshworks.atlassian.net/browse/SYMP-37
- Last piece in ensuring that logic in program matches logic in given algorithm (https://docs.google.com/drawings/d/1YrYbu8FUiUz3SU1HwQ9nlSmkQBTdMjsVYwTinqCZnS0)
- exit early with recommendation for no test when no symptoms
- exit early with recommendation for test when yes to any vulnerable groups questions
=> SYMP-37 | Exit early when user answers "yes" to vulnerable populations questions

apps/web/src/forms/SymptomChecker.tsx, apps/web/src/types/index.ts, apps/web/src/utils/determineReccomendation.ts
Ticket: https://freshworks.atlassian.net/jira/software/c/projects/SYMP/boards/288?modal=detail&selectedIssue=SYMP-67
=> SYMP-67 | End on Vulnerable Populations question

apps/web/src/styles/globals.css
Ticket: https://freshworks.atlassian.net/browse/SYMP-69
- added a CSS rule
=> SYMP-69 | Radio Inputs scaling

apps/web/public/locales/en/translation.json, apps/web/src/components/Home.tsx
Updating the last updated date to reflect launch date.
=> SYMP 102 | Last Updated Date 

apps/web/cypress/fixtures/questions.json, apps/web/public/locales/en/translation.json
Minor edit to recommendation on fever wording
=> SYMP 105 | Edit Recommendation 

apps/web/cypress/fixtures/questions.json, apps/web/public/locales/en/translation.json, apps/web/src/results/ResultRapidTest.tsx
Ticket: https://freshworks.atlassian.net/browse/SYMP-107
=> SYMP-107 | Add BCCDC link to rapid test recommendation

apps/web/public/locales/en/translation.json, apps/web/src/components/Home.tsx
Changed last updated date to September 28, 2022.
=> SYMP-108 | Last Updated Date

Makefile, terraform/app.tf
Fixed an issue where the certificate was not being access properly, causing tf apply to fail.
=> Symp tf hotfix

apps/web/public/locales/en/severity.json
Fixed grammatical error on shortness of breath question.
=> SYMP 110 | Fixed Grammatical Error 

apps/web/public/locales/en/translation.json, apps/web/src/components/Home.tsx
Updated last updated date to November 17th 2022
=> Updated last updated date

yarn.lock
Updated express and qs to fix npm warnings.
=> SYMP-111 Fix vulnerabilities in yarn packages

.github/workflows/deploy-dev.yml, .github/workflows/deploy-prod.yml, .github/workflows/deploy-test.yml
It looks like our slack integration is failing and breaking our deployments. I have removed them. In future we should add Teams notifications.
=> Hotfix- Removed slack notifications

apps/api/package.json, yarn.lock
Hi all, 
I just updated all the packages flagged by dependabot as having vulnerabilities. The exception is dicer, which has no fix yet.
=> Updated yarn to address dependabot warnings
